### PR TITLE
Fixed Default view error in Portfolio overview

### LINKED ISSUE #428: Issues when using default view in web part properties for Portfolio overview web part
**Describe the bug**
Web part portfolio overview crashes when setting default view in web part property pane.

**To Reproduce**

1. Go to SitePages/Porteføljeoversikt.aspx
2. Edit page
3. Set a value for "Standardvisning" in property pane
4. Refresh SitePages/Porteføljeoversikt.aspx

**Expected behavior**
The default view selected in web part property pane should be the default view. Not make the page crash.

**Screenshots**
image

**About your setup**
N/A

**Additional context**

### PR DESCRIPTION
**Pull request by Petterandre**
### Your checklist for this pull request

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your main!
- [x] Make sure you are making a pull request against the **dev** branch (left side). Also you should start *your branch* off *dev*.
- [x] Check the commit's or even all commits' message 
- [x] Check if your code additions will fail linting checks
- [x] Remember: Add PR description to [CHANGELOG](https://github.com/Puzzlepart/prosjektportalen365/blob/dev/CHANGELOG.md) with the ID that matches this PR

### Description

Fixes default view crash on Portfolio overview. Although the variable was initialized as type string, the typeof was number, so adding .toString() fixed the comparison.

### How to test

1. Go to SitePages/Porteføljeoversikt.aspx
2. Edit page
3. Set a value for "Standardvisning" in property pane
4. Refresh SitePages/Porteføljeoversikt.aspx

### Relevant issues (if applicable)

Closes #428 

💔Thank you!

### CODE REVIEW

File: SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx [hunk 1]
```diff
@@ -446,7 +446,7 @@ export class PortfolioOverview extends Component<IPortfolioOverviewProps, IPortf
         throw new PortfolioOverviewErrorMessage(strings.ViewNotFoundMessage, MessageBarType.error)
       }
     } else if (defaultViewId) {
-      currentView = _.find(views, (v) => v.id.toString() === defaultViewId)
+      currentView = _.find(views, (v) => v.id.toString() === defaultViewId.toString())
```
Comment (olemp) [inline SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx:449]: Isn't `defaultViewId` a string already?

Comment (olemp) [reply SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx:449]: cc @Petterandre

Comment (Petterandre) [reply SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx:449]: It should be, but i logged typeof(defaultViewId) and for some reason it was number. VSCode says it is defined as a string, but at runtime it isn't for some reason.

Comment (Petterandre) [reply SharePointFramework/PortfolioWebParts/src/components/PortfolioOverview/index.tsx:449]: image
